<?php

namespace App\Http\Requests;

use App\Account;
use Illuminate\Foundation\Http\FormRequest;

class RegisterRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'email' => 'required|email',
            'password' => 'required|min:6',
            'firstName' => 'required|min:2',
            'lastName' => 'required|min:2',
            'address' => 'required|min:6',
            'city' => 'required',
            'phone' => 'required|numeric',
//            'term' => 'required',
            'sex' => 'required',
            'birthDate' => 'required',
        ];
    }

    public function messages()
    {
        return [

        ]; // TODO: Change the autogenerated stub
    }

    public function withValidator($validator)
    {
        if($validator->fails()){
            return ;
        }else{
            $validator->after(
                function ($validator) {
                $find_account = Account::where('email',$this->email)->get()->first();
                    if ($find_account != null) {
                        if ($find_account->email){
                        return $validator->errors()->add('email', 'This email have been already used !');
                    }
                }
            });
        }
    }


}
